# docker-compose.yml : easily bring up a complete environment for local development

version: "3.8"
services:
  gateway:
    build:
      context: ./tools/gateway
    environment:
      - PORT=${GATEWAY_PORT}
    network_mode: "host"
  db:
    build:
      args:
        - UID=${USERID}
        - USER=${USERNAME}
      context: ./tools/localdb
    depends_on:
      - gateway
    environment:
      - PORT=${DB_PORT}
    network_mode: "host"
    volumes:
      - ./tools/localdb/.storage:/data/db
  web-backend:
    build:
      # we need access to some other packages in order to build the backend
      context: ./packages
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    environment:
      - DB_DRIVER=${WEB_BACKEND_DB_DRIVER}
      - DB_PASS=${WEB_BACKEND_DB_PASS}
      - DB_URI=${WEB_BACKEND_DB_URI}
      - DB_USER=${WEB_BACKEND_DB_USER}
      - PORT=${WEB_BACKEND_PORT}
      - SESSION_SECRET=${WEB_BACKEND_SESSION_SECRET}
    network_mode: "host"
